jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      dev:
        atom_channel: dev
        atom_name: atom-dev
      beta:
        atom_channel: beta
        atom_name: atom-beta
      stable:
        atom_channel: stable
        atom_name: atom
  variables:
    display: ":99"
  steps:
  - template: script/azure-pipelines/linux-install.yml
    parameters:
      atom_channel: $(atom_channel)
      atom_name: $(atom_name)
  - bash: |
      "/tmp/atom/usr/bin/${ATOM_NAME}" --test test/
    displayName: run tests
    env:
      TEST_JUNIT_XML_PATH: $(Agent.HomeDirectory)/test-results.xml
      FORCE_COLOR: 0
      MOCHA_TIMEOUT: 60000
      UNTIL_TIMEOUT: 30000
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: $(Agent.HomeDirectory)/test-results.xml
      testRunTitle: Linux $(atom_channel)
    condition: succeededOrFailed()

- job: MacOS
  pool:
    vmImage: macos-10.13
  strategy:
    matrix:
      dev:
        ATOM_CHANNEL: dev
        ATOM_APP: Atom Dev.app
      beta:
        ATOM_CHANNEL: beta
        ATOM_APP: Atom Beta.app
      stable:
        ATOM_CHANNEL: stable
        ATOM_APP: Atom.app
  steps:
  - bash: |
      set -x
      curl -s -L "https://atom.io/download/mac?channel=${ATOM_CHANNEL}" \
        -H 'Accept: application/octet-stream' \
        -o "atom.zip"
      mkdir -p /tmp/atom
      unzip -q atom.zip -d /tmp/atom
    displayName: install Atom
  - bash: '"/tmp/atom/${ATOM_APP}/Contents/Resources/app/apm/bin/apm" ci'
    displayName: install dependencies
  - bash: '"/tmp/atom/${ATOM_APP}/Contents/Resources/app/atom.sh" --test test/'
    displayName: run tests
    env:
      TEST_JUNIT_XML_PATH: $(Agent.HomeDirectory)/test-results.xml
      FORCE_COLOR: 0
      MOCHA_TIMEOUT: 60000
      UNTIL_TIMEOUT: 30000
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: $(Agent.HomeDirectory)/test-results.xml
      testRunTitle: MacOS $(ATOM_CHANNEL)
    condition: succeededOrFailed()

- job: Windows
  pool:
    vmImage: vs2015-win2012r2
  strategy:
    matrix:
      dev:
        ATOM_CHANNEL: dev
        ATOM_DIRECTORY: Atom Dev
      beta:
        ATOM_CHANNEL: beta
        ATOM_DIRECTORY: Atom Beta
      stable:
        ATOM_CHANNEL: stable
        ATOM_DIRECTORY: Atom
  steps:
  - powershell: |
      Set-StrictMode -Version Latest
      $script:ATOMROOT = "$env:AGENT_HOMEDIRECTORY/atom"

      Write-Host "Downloading latest Atom release"
      $source = "https://atom.io/download/windows_zip?channel=$env:ATOM_CHANNEL"
      $destination = "atom.zip"

      (New-Object System.Net.WebClient).DownloadFile($source, $destination)
      Expand-Archive -Path "atom.zip" -DestinationPath $script:ATOMROOT
    displayName: install Atom
  - powershell: |
      Set-StrictMode -Version Latest
      $script:ATOMROOT = "$env:AGENT_HOMEDIRECTORY/atom"
      $script:APM_SCRIPT_PATH = "$script:ATOMROOT\$env:ATOM_DIRECTORY\resources\app\apm\bin\apm.cmd"

      Write-Host "Installing package dependencies"
      & "$script:APM_SCRIPT_PATH" ci
      if ($LASTEXITCODE -ne 0) {
        Write-Host "Dependency installation failed"
        $host.SetShouldExit($LASTEXITCODE)
        exit
      }
    displayName: install dependencies
  - powershell: |
      Set-StrictMode -Version Latest
      $script:ATOMROOT = "$env:AGENT_HOMEDIRECTORY/atom"
      $script:ATOM_SCRIPT_PATH = "$script:ATOMROOT\$env:ATOM_DIRECTORY\resources\cli\atom.cmd"

      # Normalize %TEMP% as a long (non 8.3) path.
      $env:TEMP = (Get-Item -LiteralPath $env:TEMP).FullName

      $env:ELECTRON_NO_ATTACH_CONSOLE = "true"
      [Environment]::SetEnvironmentVariable("ELECTRON_NO_ATTACH_CONSOLE", "true", "User")
      $env:ELECTRON_ENABLE_LOGGING = "YES"
      [Environment]::SetEnvironmentVariable("ELECTRON_ENABLE_LOGGING", "YES", "User")

      Write-Host "Running tests"
      & "$script:ATOM_SCRIPT_PATH" --test test 2>&1 | %{ "$_" }

      if ($LASTEXITCODE -ne 0) {
        Write-Host "Specs Failed"
        $host.SetShouldExit($LASTEXITCODE)
        exit
      }
    displayName: run tests
    env:
      TEST_JUNIT_XML_PATH: $(Agent.HomeDirectory)/test-results.xml
      FORCE_COLOR: 0
      ATOM_GITHUB_SKIP_SYMLINKS: 1
      MOCHA_TIMEOUT: 60000
      UNTIL_TIMEOUT: 30000
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: $(Agent.HomeDirectory)/test-results.xml
      testRunTitle: Windows $(ATOM_CHANNEL)
    condition: succeededOrFailed()

- job: Lint
  pool:
    vmImage: ubuntu-16.04
  variables:
    display: ":99"
    ATOM_CHANNEL: dev
  steps:
  - template: script/azure-pipelines/linux-install.yml
  - bash: /tmp/atom/usr/share/atom-dev/resources/app/apm/node_modules/.bin/npm run lint
    displayName: run the linter

- job: Snapshot
  pool:
    vmImage: ubuntu-16.04
  variables:
    display: ":99"
    ATOM_CHANNEL: dev
  steps:
  - template: script/azure-pipelines/linux-install.yml
  - bash: /tmp/atom/usr/bin/atom-dev --test test/
    displayName: run tests
    env:
      ATOM_GITHUB_TEST_SUITE: snapshot
      TEST_JUNIT_XML_PATH: $(Agent.HomeDirectory)/test-results.xml
      FORCE_COLOR: 0
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: $(Agent.HomeDirectory)/test-results.xml
      testRunTitle: Snapshot
    condition: succeededOrFailed()
